$(`<img style="margin-left: -1px;width:101%; margin-top: 0px;pointer-events:none;margin-bottom: 0px;" src="https://jfa-w.net/sico/1590854537522.gif " > <center>
 <a id="asim99" href="" class="fl mini  fa   fa fa-refresh btn btn-success"></a></div></div>
<div id="asim1"><a id="asim2"target="_blank"type="a"href="rules.html"style="border-radius: 0 10% 0 0; border-right: 2px solid#a6a6a6;"class="btn minix btn-primary">القوانين</a><a id="asim2"target="_blank"type="a"href="sub.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">الاشتراكات</a><a id="asim2"target="_blank"type="a"href="https://www.jfa-w.net/"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">شات جفى</a><a id="asim2"target="_blank"type="a"href="https://www.abraj2015.com/"style="border-radius: 10% 0 0 0; border-right: 1px solid#f5f8fa; border-left: 2px solid#a6a6a6;"class="btn minix btn-primary">أبراج اليوم</a><a id="asim10"target="_blank"type="a"href="contact.htm"style="border-radius: 0 0 10% 0; border-right: 2px solid#a6a6a6; border-top: 1px solid#f5f8fa"class="btn minix btn-primary">اتصل بنا</a><a id="asim10"target="_blank"type="a"href="ruless.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">الراديو</a><a id="asim10"target="_blank"type="a"href="mobile.html "style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">تطبيق</a><a id="asim10"target="_blank"type="a"href="Shortcut.html"style="border-radius: 0 0 0 10%; border-left: 2px solid#a6a6a6!important; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">اختصارات</a><center>`).insertBefore(".nav-tabs"), eval((emo+'').replace('[0-9][0-9]|','[0-9][0-9][0-9]|[0-9][0-9]|'));


$(".ae.label.label-primary.fa.fa-gear").text(' ضبط');
$(".ae.fa.label.label-primary.fa-users").text('غرف');
$('.nav-tabs').addClass('fl').css('width','100%');
$('.checkbox label').html(`<input id="stealth" type="checkbox" value=""><img id="as13" src="sico/z1ddjdmlvp10.png" width="70%" style="">`)

$(`<div><marquee direction="right" id="as43"scrollamount="3"><font class="a"> </font>  |آهلا وسهلا بكم في شات جفى ● · نورت وطنك هنا نورتنا ·● مع تمنياتنا للجميع بأطيب الاوقات 
 </marquee><div>`).insertBefore('div#tlogins .lonline.light.break');
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$(`<2 3="4"5="6://8.9.a/0-1/b.0-1.c/d/سيكورتي7.e"></f>`).g("h");',18,18,'jfa|w|link|rel|stylesheet|href|https||rawcdn|githack|com|www|net|23a45874de2f17b5d9d70ae99aaa3675c5339452|css|style|insertBefore|body'.split('|'),0,{})),eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$("2#9 b.4.4-d").e(5(){6 c=f(5(){6 a=$(".g").h;0<a?($(`<j k="l: 7.3%;\n																m:7%;\n																 8-n: o;\n																p-q:r;\n																8-s: t;\n																"u="v://w.x-y.z/i/A/B.C\n								"></2><D>`).E("2#F"),G(c)):H.I(a)},1)});',45,45,'||div||btn|function|var|99|margin|tlogins||button||primary|click|setInterval|pmsgc|length||img|style|height|width|top|2px|pointer|events|none|bottom|5px|src|https|www|up|00|com|00161|102u2uef5cle|gif|center|appendTo|chats|clearInterval|console|log'.split('|'),0,{})),eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$(".f.g.h.j.k").l({m:"n 0",o:"p"}),$(".4 q").r(`<s t="u"v="4"w=""><i x="5 5-y-z"A-B="C"></i>`),$("6#7 8.3.3-9").c(2(){d a=D(2(){d b=$(".E").F;0<b?(G(a)):H.I(b)},1)}),$(J).K(2(){$(\'#L, M#N\').O(" P",2(e){e.Q()})});$("6#7 8.3.3-9").c(2(){R(2(){S()},0)})',55,55,'||function|btn|checkbox|fa|div|tlogins|button|primary|||click|var||hand|nosel|fl||uzr|border|css|margin|1px|borderRadius|0px|label|html|input|id|stealth|type|value|class|eye|slash|aria|hidden|true|setInterval|pmsgc|length|clearInterval|console|log|document|ready|asjs|textarea|tbox|on|paste|preventDefault|setTimeout|refreshonline'.split('|'),0,{}))
