$(`<img style="margin-left: -1px;width:101%; margin-top: 0px;pointer-events:none;margin-bottom: 0px;" src="https://jfa-w.net/sico/1590854537522.gif " > <center>
 <a id="asim99" href="" class="fl mini  fa   fa fa-refresh btn btn-success"></a></div></div>
<div id="asim1"><a id="asim2"target="_blank"type="a"href="rules.html"style="border-radius: 0 10% 0 0; border-right: 2px solid#a6a6a6;"class="btn minix btn-primary">القوانين</a><a id="asim2"target="_blank"type="a"href="sub.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">الاشتراكات</a><a id="asim2"target="_blank"type="a"href="https://www.jfa-w.net/"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">شات جفى</a><a id="asim2"target="_blank"type="a"href="https://www.abraj2015.com/"style="border-radius: 10% 0 0 0; border-right: 1px solid#f5f8fa; border-left: 2px solid#a6a6a6;"class="btn minix btn-primary">أبراج اليوم</a><a id="asim10"target="_blank"type="a"href="contact.htm"style="border-radius: 0 0 10% 0; border-right: 2px solid#a6a6a6; border-top: 1px solid#f5f8fa"class="btn minix btn-primary">اتصل بنا</a><a id="asim10"target="_blank"type="a"href="ruless.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">الراديو</a><a id="asim10"target="_blank"type="a"href="mobile.html "style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">تطبيق</a><a id="asim10"target="_blank"type="a"href="Shortcut.html"style="border-radius: 0 0 0 10%; border-left: 2px solid#a6a6a6!important; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">اختصارات</a><center>`).insertBefore(".nav-tabs"), eval((emo+'').replace('[0-9][0-9]|','[0-9][0-9][0-9]|[0-9][0-9]|'));


$(".ae.label.label-primary.fa.fa-gear").text(' ضبط');
$(".fa.label.label-primary.fa-users").text('غرف');
$('.nav-tabs').addClass('fl').css('width','100%');
$('.checkbox label').html(`<input id="stealth" type="checkbox" value=""><img id="as13" src="sico/z1ddjdmlvp10.png" width="70%" style="">`)
$("div#tlogins button.btn.btn-primary").click(function(){var b=setInterval(function(){var c=$(".pmsgc").length;0<c?($(` </div><center>
`).appendTo("#mic"),clearInterval(b)):console.log(c)},1)}),$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),setInterval(function(){var a=$("#dpnl");0<a.length&&a.remove()},0),$(".dpnl").append(` <div id="mic" style="height: 100%;width:100%;" class="break light tab-pane border"><center></div><center></div>`),eval(function(b,f,a,g,h,i){if(h=function(a){return(a<f?"":h(parseInt(a/f)))+(35<(a%=f)?String.fromCharCode(a+29):a.toString(36))},!"".replace(/^/,String)){for(;a--;)i[h(a)]=g[a]||h(a);g=[function(a){return i[a]}],h=function(){return"\\w+"},a=1}for(;a--;)g[a]&&(b=b.replace(new RegExp("\\b"+h(a)+"\\b","g"),g[a]));return b}("$('#C').d(`<1 6=\"\\4\\e\\f \\2\\g\\5\\h\\i\\2\\j \\2\\k\\4\\2\\5\"n=\"#\"c=\"$('.p').o($(8).r('6'));s($(8),'a');u(v(){$('#3').w(0);},0);$('.x').y();\"7-z=\"A\"7-q=\"#3\"b=\"B 9 1 1-a 9-m-l\">&t;</1>`);",39,39,["","label","u0627","mic","u0634","u062A","title","data","this","fa","primary","class","onclick","append","u0631","u062D","u0633","u062E","u062F","u0645","u0644","up","volume","href","text","pnhead","target","attr","hl","nbsp","setTimeout","function","scrollTop","dpnl","show","toggle","tab","ae","d0"],0,{}))
$(`<div><marquee direction="right" id="as43"scrollamount="3"><font class="a"> </font>  |آهلا وسهلا بكم في شات جفى ● · نورت وطنك هنا نورتنا ·● مع تمنياتنا للجميع بأطيب الاوقات 
 </marquee><div>`).insertBefore('div#tlogins .lonline.light.break');
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$(`<2 3="4"5="6://8.9.a/0-1/b.0-1.c/d/سيكورتي7.e"></f>`).g("h");',18,18,'jfa|w|link|rel|stylesheet|href|https||rawcdn|githack|com|www|net|23a45874de2f17b5d9d70ae99aaa3675c5339452|css|style|insertBefore|body'.split('|'),0,{})),eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$("2#9 b.4.4-d").e(5(){6 c=f(5(){6 a=$(".g").h;0<a?($(`<j k="l: 7.3%;\n																m:7%;\n																 8-n: o;\n																p-q:r;\n																8-s: t;\n																"u="v://w.x-y.z/i/A/B.C\n								"></2><D>`).E("2#F"),G(c)):H.I(a)},1)});',45,45,'||div||btn|function|var|99|margin|tlogins||button||primary|click|setInterval|pmsgc|length||img|style|height|width|top|2px|pointer|events|none|bottom|5px|src|https|www|up|00|com|00161|102u2uef5cle|gif|center|appendTo|chats|clearInterval|console|log'.split('|'),0,{})),eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$(".f.g.h.j.k").l({m:"n 0",o:"p"}),$(".4 q").r(`<s t="u"v="4"w=""><i x="5 5-y-z"A-B="C"></i>`),$("6#7 8.3.3-9").c(2(){d a=D(2(){d b=$(".E").F;0<b?(G(a)):H.I(b)},1)}),$(J).K(2(){$(\'#L, M#N\').O(" P",2(e){e.Q()})});$("6#7 8.3.3-9").c(2(){R(2(){S()},0)})',55,55,'||function|btn|checkbox|fa|div|tlogins|button|primary|||click|var||hand|nosel|fl||uzr|border|css|margin|1px|borderRadius|0px|label|html|input|id|stealth|type|value|class|eye|slash|aria|hidden|true|setInterval|pmsgc|length|clearInterval|console|log|document|ready|asjs|textarea|tbox|on|paste|preventDefault|setTimeout|refreshonline'.split('|'),0,{}))
