$(`<img style="margin-left: -1px;width:101%; margin-top: 0px;pointer-events:none;margin-bottom: 0px;" src="https://www.jfa-w.net/sico/z1dt3obvof10.gif " > <center>
<div id="asim1"><a id="asim2"target="_blank"type="a"href="rules.html"style="border-radius: 0 10% 0 0; border-right: 2px solid#a6a6a6;"class="btn minix btn-primary">القوانين</a><a id="asim2"target="_blank"type="a"href="sub.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">الاشتراكات</a><a id="asim2"target="_blank"type="a"href="https://www.jfa-w.net/"style="border-radius: 0%; border-right: 1px solid#f5f8fa;"class="btn minix btn-primary">شات جفى</a><a id="asim2"target="_blank"type="a"href="https://www.abraj2015.com/"style="border-radius: 10% 0 0 0; border-right: 1px solid#f5f8fa; border-left: 2px solid#a6a6a6;"class="btn minix btn-primary">أبراج اليوم</a><a id="asim10"target="_blank"type="a"href="contact.htm"style="border-radius: 0 0 10% 0; border-right: 2px solid#a6a6a6; border-top: 1px solid#f5f8fa"class="btn minix btn-primary">اتصل بنا</a><a id="asim10"target="_blank"type="a"href="ruless.html"style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">الراديو</a><a id="asim10"target="_blank"type="a"href="mobile.html "style="border-radius: 0%; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">تطبيق</a><a id="asim10"target="_blank"type="a"href="Shortcut.html"style="border-radius: 0 0 0 10%; border-left: 2px solid#a6a6a6!important; border-right: 1px solid#f5f8fa; border-top: 1px solid#f5f8fa;"class="btn minix btn-primary">اختصارات</a><center>`).insertBefore(".nav-tabs"), eval((emo+'').replace('[0-9][0-9]|','[0-9][0-9][0-9]|[0-9][0-9]|'));
$(`<a href="https://play.google.com/store/apps/details?id=com.jfa.net" target="_blank" style=" font-family:'El Messiri',sans-serif;
  width:107px;
  color:#ff0000;
  text-decoration:none;
  margin-right:5px;
  margin-left:2px;
  text-align:center;
  float:right;
  border-radius:5px;
  border-color:#F2F2F2;
  padding:3px;
  " class="border" ><i class="fa fa-android"></i> التطبيق</a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');
$(".ae.label.label-primary.fa.fa-gear").text(' ضبط');
$(".ae.fa.label.label-primary.fa-users").text('غرف');
$('.nav-tabs').addClass('fl').css('width','100%');
$('.checkbox label').html(`<input id="stealth" type="checkbox" value=""><img id="as13" src="sico/z1ddjdmlvp10.png" width="70%" style="">`)
$("div#tlogins button.btn.btn-primary").click(function(){var b=setInterval(function(){var c=$(".pmsgc").length;0<c?($(` </div><center>
`).appendTo("#mic"),clearInterval(b)):console.log(c)},1)}),$("div#tlogins button.btn.btn-primary").click(function(){setTimeout(function(){refreshonline()},0)}),setInterval(function(){var a=$("#dpnl");0<a.length&&a.remove()},0),$(".dpnl").append(` <div id="mic" style="height: 100%;width:100%;" class="break light tab-pane border"><center></div><center></div>`),eval(function(b,f,a,g,h,i){if(h=function(a){return(a<f?"":h(parseInt(a/f)))+(35<(a%=f)?String.fromCharCode(a+29):a.toString(36))},!"".replace(/^/,String)){for(;a--;)i[h(a)]=g[a]||h(a);g=[function(a){return i[a]}],h=function(){return"\\w+"},a=1}for(;a--;)g[a]&&(b=b.replace(new RegExp("\\b"+h(a)+"\\b","g"),g[a]));return b}("$('#C').d(`<1 6=\"\\4\\e\\f \\2\\g\\5\\h\\i\\2\\j \\2\\k\\4\\2\\5\"n=\"#\"c=\"$('.p').o($(8).r('6'));s($(8),'a');u(v(){$('#3').w(0);},0);$('.x').y();\"7-z=\"A\"7-q=\"#3\"b=\"B 9 1 1-a 9-m-l\">&t;</1>`);",39,39,["","label","u0627","mic","u0634","u062A","title","data","this","fa","primary","class","onclick","append","u0631","u062D","u0633","u062E","u062F","u0645","u0644","up","volume","href","text","pnhead","target","attr","hl","nbsp","setTimeout","function","scrollTop","dpnl","show","toggle","tab","ae","d0"],0,{}))
$(`<div><marquee direction="right" id="as43"scrollamount="3"><font class="a"> </font>  |آهلا وسهلا بكم في شات جفى ● · نورت وطنك هنا نورتنا ·● مع تمنياتنا للجميع بأطيب الاوقات 
 </marquee><div>`).insertBefore('div#tlogins .lonline.light.break');
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('D f=["\\r\\l\\a\\m","\\n\\g\\5\\3\\b\\4\\E\\3\\c\\l\\b\\3","\\s\\h\\n\\g\\t\\u\\b\\3\\h\\v\\i\\5\\4\\m\\h\\3\\5\\j\\3\\3\\4\\i\\u\\j\\b\\3\\c\\v\\i\\j\\4\\4\\F\\5\\G\\6\\6\\b\\8\\9\\7\\a\\g\\d\\H\\n\\4\\j\\8\\7\\t\\d\\7\\l\\I\\6\\w\\c\\8\\x\\9\\6\\9\\9\\9\\d\\w\\c\\8\\x\\9\\d\\g\\3\\4\\6\\k\\k\\8\\o\\e\\a\\p\\e\\8\\3\\p\\J\\3\\k\\K\\q\\o\\a\\p\\e\\3\\r\\q\\e\\3\\y\\z\\7\\q\\A\\a\\k\\y\\o\\e\\c\\3\\7\\7\\A\\6\\L\\B\\M\\N\\O\\P\\B\\z\\d\\7\\5\\5\\i\\C\\s\\6\\5\\4\\m\\h\\3\\C"];$(f[2])[f[1]](f[0])',52,52,'|||x65|x74|x73|x2F|x63|x61|x77|x64|x72|x66|x2E|x35|_0x8912|x6E|x6C|x22|x68|x37|x6F|x79|x69|x30|x36|x31|x62|x3C|x6B|x20|x3D|x6A|x2D|x39|x32|x38|u064A|x3E|var|x42|x70|x3A|x67|x6D|x34|x33|u0633|u0643|u0648|u0631|u062A'.split('|'),0,{})),eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('$("2#9 b.4.4-d").e(5(){6 c=f(5(){6 a=$(".g").h;0<a?($(`<i j="k: 7.3%;\n										l:7%;\n										 8-m: n;\n										o-p:q;\n										8-r: s;\n										"t="u://v.w.x/y/z.A\n		"></2><B>`).C("2#D"),E(c)):F.G(a)},1)});',43,43,'||div||btn|function|var|99|margin|tlogins||button||primary|click|setInterval|pmsgc|length|img|style|height|width|top|2px|pointer|events|none|bottom|5px|src|http|www|m9c|net|uploads|15774506531|gif|center|appendTo|chats|clearInterval|console|log'.split('|'),0,{}))
